📜 Landing page
SallaApp/theme-raed pull request #154
Opened 2022-12-15 11:50 UTC by eslamoo

- Normal landing page
- Expired offer layout

- Not found layout

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* 

What is the current behaviour? (You can also link to an open issue here)

* 

What is the new behaviour? (You can also link to the ticket here)

* 

Does this PR introduce a breaking change?

* 

Screenshots (If appropriate)

*

2023-01-22 16:57 UTC, SallaDev commented
> The branch `static-landing-page` of https://github.com/SallaApp/theme-raed/pull/154 has been synced from master..✅

2023-01-23 07:29 UTC, SallaDev commented
> The branch `static-landing-page` of https://github.com/SallaApp/theme-raed/pull/154 has Merge conflict❌

2023-01-23 10:26 UTC, SallaDev commented
> The branch `static-landing-page` of https://github.com/SallaApp/theme-raed/pull/154 has Merge conflict❌

2023-01-29 12:34 UTC, SallaDev commented
> The branch `static-landing-page` of https://github.com/SallaApp/theme-raed/pull/154 has been synced from master..✅

2023-01-30 06:57 UTC, jalmatari requested changes

2023-01-30 06:57 UTC, jalmatari commented on src/views/pages/landing-page.twig
> +| page.slug    | string                |             |
add documentation for landing object, use: https://www.tablesgenerator.com/markdown_tables

2023-01-30 06:57 UTC, jalmatari commented on src/views/pages/landing-page.twig
> +                {% endif %}
try to make it like this:
```
{% set hide_add_btn=true %}
{% set show_quantity=landing.show_quantity %}
{% set products=landing.products %}
{% set title=trans('pages.offer.included_products') %}
{% if landing.is_slider %}
    {% include 'components.home.products-slider' %}
{% else %}
    {% include 'components.home.fixed-products' %}
{% endif %}
```

2023-01-30 09:32 UTC, SallaDev commented
> The branch `static-landing-page` of https://github.com/SallaApp/theme-raed/pull/154 has been synced from master..✅

2023-01-31 15:43 UTC, SallaDev commented
> The branch `static-landing-page` of https://github.com/SallaApp/theme-raed/pull/154 has been synced from master..✅

2023-02-01 07:01 UTC, SallaDev commented
> The branch `static-landing-page` of https://github.com/SallaApp/theme-raed/pull/154 has Merge conflict❌

2023-02-01 09:45 UTC, SallaDev commented
> The branch `static-landing-page` of https://github.com/SallaApp/theme-raed/pull/154 has Merge conflict❌

2023-02-01 10:48 UTC, SallaDev commented
> The branch `static-landing-page` of https://github.com/SallaApp/theme-raed/pull/154 has Merge conflict❌

2023-02-02 09:36 UTC, SallaDev commented
> The branch `static-landing-page` of https://github.com/SallaApp/theme-raed/pull/154 has Merge conflict❌

2023-02-05 12:24 UTC, SallaDev commented
> The branch `static-landing-page` of https://github.com/SallaApp/theme-raed/pull/154 has been synced from master..✅

2023-02-08 09:53 UTC, SallaDev commented
> The branch `static-landing-page` of https://github.com/SallaApp/theme-raed/pull/154 has Merge conflict❌

2023-02-08 12:23 UTC, AIMSemo commented
/merge

2023-02-08 12:23 UTC, merged

2023-02-08 12:23 UTC, SallaDev commented
https://github.com/SallaApp/Store/pull/3946 ` is closed ❗️`

-------------------
https://github.com/SallaApp/theme-raed/pull/154 ` is been merged ✅`

-------------------