buy gift widget subtitle
SallaApp/theme-raed pull request #169
Opened 2023-01-09 15:53 UTC by ibrahim-gabr

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* 

What is the current behaviour? (You can also link to an open issue here)

* 

What is the new behaviour? (You can also link to the ticket here)

* 

Does this PR introduce a breaking change?

* 
STORE-62
Screenshots (If appropriate)

*

2023-01-09 16:38 UTC, jalmatari requested changes

2023-01-09 16:38 UTC, jalmatari commented on src/views/pages/product/single.twig
> +    console.log({{ store_text | json_encode | raw}});
What is this🌚

2023-01-09 18:08 UTC, zymawy approved these changes

2023-01-10 05:55 UTC, jalmatari approved these changes

2023-01-10 05:55 UTC, merged