✨ Support New Twilight Components
SallaApp/theme-raed pull request #192
Opened 2023-03-06 10:28 UTC by eslamoo

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* 

What is the current behaviour? (You can also link to an open issue here)

* 

What is the new behaviour? (You can also link to the ticket here)

* 

Does this PR introduce a breaking change?

* 

Screenshots (If appropriate)

*

2023-03-12 12:05 UTC, salkhwlani commented on src/views/components/home/latest-products.twig
> +    <salla-products-list></salla-products-list>
```html
<salla-products-list source="latest"></salla-products-list>
```

2023-03-12 12:05 UTC, salkhwlani commented on src/views/pages/landing-page.twig
> +                    <salla-products-slider block-title="{{trans('pages.offer.included_products')}}" display-all-url></salla-products-slid
```html
<salla-products-list source="landing-page"></salla-products-list>
```

2023-03-12 12:06 UTC, salkhwlani commented on src/views/pages/landing-page.twig
> +                        <salla-products-list class="{{is_vertical ? 'vertical-products' : 'horizontal-products'}}"></salla-products-list>
```html
<salla-products-list source="landing-page"></salla-products-list>```

2023-03-12 12:06 UTC, salkhwlani commented on src/views/pages/partials/product/card-mini.twig
> +<salla-product-card shadow-on-hover product="{{product}}" minimal></salla-product-card>
drop the file, and use this directly on the place

2023-03-12 12:07 UTC, salkhwlani commented on src/views/pages/partials/product/card.twig
> +<salla-product-card shadow-on-hover product="{{product}}" {{is_special ? 'is-special' : ''}} {{is_horizontal ? 'horizontal' : ''}}></salla-product-card>
Drop this file and use the component directly on the place

2023-03-12 12:07 UTC, salkhwlani commented on src/views/pages/product/index.twig
> +                    <salla-products-list></salla-products-list>
```html
<salla-products-list source="page.slug" source-value="page.id"></salla-products-list>
```

2023-03-12 12:08 UTC, salkhwlani commented on src/views/pages/product/single.twig
> +        <salla-products-slider block-title="{{trans('pages.products.similar_products')}}" display-all-url></salla-products-slider>
<salla-products-list source="related" source-value="product.id"></salla-products-list>

2023-03-12 12:09 UTC, salkhwlani requested changes

2023-03-12 12:09 UTC, salkhwlani commented on src/views/pages/partials/product/card-full-image.twig
> +<salla-product-card shadow-on-hover product="{{product}}" full-image></salla-product-card>
drop the file, and use this directly on the place

2023-03-15 10:43 UTC, SallaDev commented
> The branch `support-product-components` of https://github.com/SallaApp/theme-raed/pull/192 has been synced from master..✅

2023-03-15 12:20 UTC, SallaDev commented
> The branch `support-product-components` of https://github.com/SallaApp/theme-raed/pull/192 has been synced from master..✅

2023-03-15 13:00 UTC, SallaDev commented
> The branch `support-product-components` of https://github.com/SallaApp/theme-raed/pull/192 has Merge conflict❌

2023-03-15 13:11 UTC, jalmatari approved these changes

2023-03-15 13:57 UTC, jalmatari approved these changes

2023-03-15 13:58 UTC, merged