New feedback page
SallaApp/theme-raed pull request #211
Opened 2023-05-02 22:47 UTC by egkrinkel

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* 

What is the current behaviour? (You can also link to an open issue here)

* 

What is the new behaviour? (You can also link to the ticket here)

* 

Does this PR introduce a breaking change?

* 

Screenshots (If appropriate)

*

2023-05-03 15:08 UTC, SallaDev commented
> The branch `new-feedback-page` of https://github.com/SallaApp/theme-raed/pull/211 has Merge conflict❌

2023-05-07 12:40 UTC, SallaDev commented
> The branch `new-feedback-page` of https://github.com/SallaApp/theme-raed/pull/211 has Merge conflict❌

2023-05-08 17:39 UTC, SallaDev commented
> The branch `new-feedback-page` of https://github.com/SallaApp/theme-raed/pull/211 has Merge conflict❌

2023-05-21 08:44 UTC, SallaDev commented
> The branch `new-feedback-page` of https://github.com/SallaApp/theme-raed/pull/211 has been synced from master..✅

2023-05-22 08:42 UTC, jalmatari requested changes

2023-05-22 08:42 UTC, jalmatari commented on src/views/pages/partials/single-comment.twig
remove the usage for: `hide_user`

2023-05-30 14:09 UTC, SallaDev commented
> The branch `new-feedback-page` of https://github.com/SallaApp/theme-raed/pull/211 has been synced from master..✅

2023-05-30 14:09 UTC, SallaDev commented
> The branch `new-feedback-page` of https://github.com/SallaApp/theme-raed/pull/211 has been synced from master..✅

2023-06-04 06:58 UTC, jalmatari approved these changes

2023-06-06 06:37 UTC, merged