refactor(themes): validate product options before making update price request
SallaApp/theme-raed pull request #347
Opened 2024-04-24 13:58 UTC by Ahmed-Basalib10

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* Refactor 

What is the current behaviour? (You can also link to an open issue here)

* Making http request whenever product options changes without validations

What is the new behaviour? (You can also link to the ticket here)

* Validate product options before making the request

Does this PR introduce a breaking change?

* No

Screenshots (If appropriate)

*

2024-04-24 15:50 UTC, jalmatari requested changes

2024-04-24 15:50 UTC, jalmatari commented on src/assets/js/product.js
> +          const isValid = await productOptions?.reportValidity();
why you are calling the reportValidity on the productOptions?
call it on the form and remove the await and the async

2024-04-25 06:29 UTC, jalmatari approved these changes

2024-04-25 06:29 UTC, jalmatari commented
/merge

2024-04-25 06:29 UTC, merged

2024-04-25 06:29 UTC, SallaDev commented
https://github.com/SallaApp/theme-raed/pull/347 is been merged ✅

-------------------

Merge by: @jalmatari