Feature/td 552 support custom wishlist card
SallaApp/theme-raed pull request #376
Opened 2024-05-20 13:53 UTC by W-O-X-Y

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* feature

What is the current behaviour? (You can also link to an open issue here)

* 

What is the new behaviour? (You can also link to the ticket here)

* Add custom wishlist card custom component

Does this PR introduce a breaking change?

* 

Screenshots (If appropriate)

*

2024-05-21 14:52 UTC, jalmatari requested changes

2024-05-21 14:52 UTC, jalmatari commented on src/views/layouts/master.twig
> +    <script defer src="{{ 'wishlist-card.js'|asset }}"></script>
add new block, call it `head_start` for example and pass this from wishlist page

2024-05-22 07:55 UTC, jalmatari approved these changes

2024-05-22 14:24 UTC, jalmatari approved these changes

2024-05-22 14:24 UTC, jalmatari commented
/merge

2024-05-22 14:24 UTC, merged

2024-05-22 14:24 UTC, SallaDev commented
https://github.com/SallaApp/theme-raed/pull/376 is been merged ✅

-------------------

Merge by: @jalmatari