fix: display progress bar in product's card
SallaApp/theme-raed pull request #392
Opened 2024-05-29 16:39 UTC by Ahmed-S-Abduallah

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

* bug fix

What is the current behaviour? (You can also link to an open issue here)

* The progress bar is not visible

What is the new behaviour? (You can also link to the ticket here)

* The progress bar is visible

Does this PR introduce a breaking change?

* no

Screenshots (If appropriate)

*

2024-05-29 16:47 UTC, jalmatari requested changes

2024-05-29 16:47 UTC, jalmatari commented on src/assets/js/partials/product-card.js
> +          `<salla-progress-bar donation=${JSON.stringify(this.product.donation)} /></salla-progress-bar>
remove `</salla-progress-bar>`
`/>` should do the same, or remove `/` from `/>`

2024-05-29 19:14 UTC, Ahmed-S-Abduallah reviewed
fixed

2024-05-29 19:15 UTC, Ahmed-S-Abduallah reviewed
fixed

2024-05-30 06:34 UTC, jalmatari approved these changes

2024-05-30 06:35 UTC, jalmatari commented
/merge

2024-05-30 06:35 UTC, merged

2024-05-30 06:35 UTC, SallaDev commented
https://github.com/SallaApp/theme-raed/pull/392 is been merged ✅

-------------------

Merge by: @jalmatari